pipeline {
    agent {
        docker {
            image 'maven:3.8.1-ibmjava-alpine'
            args '-u root'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test and Analysis') {
            parallel {
                stage('Parallel Stage: Test') {
                    steps {
                        sh 'mvn test'
                    }
                    post {
                        always {
                            junit 'target/surefire-reports/*.xml'
                        }
                    }
                }
                stage('Parallel Stage: Sonar Analysis') {
                    steps {
                        sh 'echo Sonar Analysis'
                    }
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
